-- CarePay QRIS Gateway - Account Linkage & eKYC Schema Extension
-- Run against Khanza database (sik)

CREATE TABLE IF NOT EXISTS carepay_merchant_onboarding (
  facility_id VARCHAR(50) NOT NULL PRIMARY KEY,
  merchant_id VARCHAR(50) NOT NULL UNIQUE,
  owner_name VARCHAR(100) NOT NULL,
  owner_ktp VARCHAR(20) NOT NULL,
  onboarding_status ENUM('SUBMITTED','APPROVED','REJECTED') NOT NULL DEFAULT 'SUBMITTED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS carepay_customer_wallets (
  patient_id VARCHAR(20) NOT NULL PRIMARY KEY,
  msisdn VARCHAR(20) NOT NULL UNIQUE,
  wallet_id VARCHAR(50) DEFAULT NULL,
  token_b2b2c TEXT DEFAULT NULL,
  refresh_token TEXT DEFAULT NULL,
  binding_status ENUM('UNBOUND','PENDING_OTP','BOUND') NOT NULL DEFAULT 'UNBOUND',
  kyc_status ENUM('UNVERIFIED','IN_PROGRESS','VERIFIED','REJECTED') NOT NULL DEFAULT 'UNVERIFIED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS carepay_kyc_submissions (
  submission_id VARCHAR(36) NOT NULL PRIMARY KEY,
  entity_type ENUM('MERCHANT','CUSTOMER') NOT NULL,
  entity_id VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_entity (entity_type, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
